services:
  db:
    container_name: ${PROJECT}-db
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - '54320:5432'
  server:
    image: ${PROJECT}-server
    container_name: ${PROJECT}-server
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    expose:
      - '5002'
    ports:
      - '5002:5002'
    volumes:
      - /app/node_modules
      - .:/app
    restart: always
    networks:
      - default
